import { TransferSolution } from "../../types";

export function scenarioXiaojinkouToBaiyunAirportSouth(dateLabel: string): TransferSolution[] {
  return [
    {
      type: "transfer",
      transferStations: ["白云机场东"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "S4842",
          fromStation: "小金口",
          toStation: "白云机场东",
          departTime: "07:38",
          arriveTime: "09:39",
          durationMinutes: 121,
        },
        {
          cityTrackId: 241,
          trainName: "S4812",
          fromStation: "白云机场东",
          toStation: "白云机场南",
          departTime: "09:46",
          arriveTime: "09:51",
          durationMinutes: 5,
        },
      ],
      waitMinutes: [7],
      dateLabel,
      totalMinutes: 133,
    },
    {
      type: "transfer",
      transferStations: ["琶洲"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "S4842",
          fromStation: "小金口",
          toStation: "琶洲",
          departTime: "07:38",
          arriveTime: "09:13",
          durationMinutes: 95,
        },
        {
          cityTrackId: 241,
          trainName: "S4832",
          fromStation: "琶洲",
          toStation: "白云机场南",
          departTime: "09:59",
          arriveTime: "10:54",
          durationMinutes: 55,
        },
      ],
      waitMinutes: [46],
      dateLabel,
      totalMinutes: 196,
    },
    {
      type: "transfer",
      transferStations: ["科韵路"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "S4842",
          fromStation: "小金口",
          toStation: "科韵路",
          departTime: "07:38",
          arriveTime: "09:19",
          durationMinutes: 101,
        },
        {
          cityTrackId: 241,
          trainName: "S4832",
          fromStation: "科韵路",
          toStation: "白云机场南",
          departTime: "10:05",
          arriveTime: "10:54",
          durationMinutes: 49,
        },
      ],
      waitMinutes: [46],
      dateLabel,
      totalMinutes: 196,
    },
    {
      type: "transfer",
      transferStations: ["广州莲花山"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4712/3",
          fromStation: "小金口",
          toStation: "广州莲花山",
          departTime: "07:04",
          arriveTime: "09:03",
          durationMinutes: 119,
        },
        {
          cityTrackId: 241,
          trainName: "S4832",
          fromStation: "广州莲花山",
          toStation: "白云机场南",
          departTime: "09:38",
          arriveTime: "10:54",
          durationMinutes: 76,
        },
      ],
      waitMinutes: [35],
      dateLabel,
      totalMinutes: 230,
    },
    {
      type: "transfer",
      transferStations: ["东莞西"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4712/3",
          fromStation: "小金口",
          toStation: "东莞西",
          departTime: "07:04",
          arriveTime: "08:49",
          durationMinutes: 105,
        },
        {
          cityTrackId: 241,
          trainName: "S4832",
          fromStation: "东莞西",
          toStation: "白云机场南",
          departTime: "09:25",
          arriveTime: "10:54",
          durationMinutes: 89,
        },
      ],
      waitMinutes: [36],
      dateLabel,
      totalMinutes: 230,
    },
    {
      type: "transfer",
      transferStations: ["麻涌"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4712/3",
          fromStation: "小金口",
          toStation: "麻涌",
          departTime: "07:04",
          arriveTime: "08:56",
          durationMinutes: 112,
        },
        {
          cityTrackId: 241,
          trainName: "S4832",
          fromStation: "麻涌",
          toStation: "白云机场南",
          departTime: "09:32",
          arriveTime: "10:54",
          durationMinutes: 82,
        },
      ],
      waitMinutes: [36],
      dateLabel,
      totalMinutes: 230,
    },
  ];
}
