import { TransferSolution, DirectSolution } from "../../types";

export function scenarioYinpingToChangpingnanTransfers(dateLabel: string): TransferSolution[] {
  return [];
}

export function scenarioYinpingToChangpingnanDirect(dateLabel: string): DirectSolution[] {
  return [
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4702/3",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "07:05",
      arriveTime: "07:22",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4712/3",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "07:45",
      arriveTime: "08:02",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4722/3",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "08:30",
      arriveTime: "08:48",
      dateLabel,
      durationMinutes: 18,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4732/3",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "09:08",
      arriveTime: "09:25",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4742/3",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "09:56",
      arriveTime: "10:13",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4752/3",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "10:43",
      arriveTime: "11:04",
      dateLabel,
      durationMinutes: 21,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4764/5",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "11:35",
      arriveTime: "11:52",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4774/5",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "12:31",
      arriveTime: "12:48",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4784/5",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "13:06",
      arriveTime: "13:30",
      dateLabel,
      durationMinutes: 24,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4794/5",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "13:58",
      arriveTime: "14:15",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4806/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "14:47",
      arriveTime: "15:04",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4816/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "15:27",
      arriveTime: "15:44",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4706/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "16:11",
      arriveTime: "16:28",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4716/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "17:01",
      arriveTime: "17:18",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4726/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "17:43",
      arriveTime: "18:00",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4736/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "18:25",
      arriveTime: "18:42",
      dateLabel,
      durationMinutes: 17,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4746/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "19:17",
      arriveTime: "19:35",
      dateLabel,
      durationMinutes: 18,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4756/7",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "19:55",
      arriveTime: "20:18",
      dateLabel,
      durationMinutes: 23,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4768/9",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "20:48",
      arriveTime: "21:13",
      dateLabel,
      durationMinutes: 25,
    },
    {
      type: "direct",
      cityTrackId: 242,
      trainName: "C4778",
      startStation: "银瓶",
      endStation: "常平南",
      departTime: "21:47",
      arriveTime: "22:04",
      dateLabel,
      durationMinutes: 17,
    },
  ];
}
