import { TransferSolution } from "../../types";

export function scenarioZhangmutoudongToKeyunlu(dateLabel: string): TransferSolution[] {
  return [
    {
      type: "transfer",
      transferStation: "广州莲花山",
      leg1: {
        cityTrackId: 241,
        trainName: "C4702/3",
        fromStation: "樟木头东",
        toStation: "广州莲花山",
        departTime: "07:10",
        arriveTime: "08:26",
        durationMinutes: 76,
      },
      leg2: {
        cityTrackId: 241,
        trainName: "S4812",
        fromStation: "广州莲花山",
        toStation: "科韵路",
        departTime: "08:31",
        arriveTime: "08:58",
        durationMinutes: 27,
      },
      waitMinutes: 5,
      dateLabel,
      totalMinutes: 108,
    },
    {
      type: "transfer",
      transferStation: "东莞西",
      leg1: {
        cityTrackId: 241,
        trainName: "C4702/3",
        fromStation: "樟木头东",
        toStation: "东莞西",
        departTime: "07:10",
        arriveTime: "08:12",
        durationMinutes: 62,
      },
      leg2: {
        cityTrackId: 241,
        trainName: "S4812",
        fromStation: "东莞西",
        toStation: "科韵路",
        departTime: "08:18",
        arriveTime: "08:58",
        durationMinutes: 40,
      },
      waitMinutes: 6,
      dateLabel,
      totalMinutes: 108,
    },
    {
      type: "transfer",
      transferStation: "麻涌",
      leg1: {
        cityTrackId: 241,
        trainName: "C4702/3",
        fromStation: "樟木头东",
        toStation: "麻涌",
        departTime: "07:10",
        arriveTime: "08:19",
        durationMinutes: 69,
      },
      leg2: {
        cityTrackId: 241,
        trainName: "S4812",
        fromStation: "麻涌",
        toStation: "科韵路",
        departTime: "08:25",
        arriveTime: "08:58",
        durationMinutes: 33,
      },
      waitMinutes: 6,
      dateLabel,
      totalMinutes: 108,
    },
    {
      type: "transfer",
      transferStation: "西平西",
      leg1: {
        cityTrackId: 241,
        trainName: "C4702/3",
        fromStation: "樟木头东",
        toStation: "西平西",
        departTime: "07:10",
        arriveTime: "07:59",
        durationMinutes: 49,
      },
      leg2: {
        cityTrackId: 241,
        trainName: "S4842",
        fromStation: "西平西",
        toStation: "科韵路",
        departTime: "08:37",
        arriveTime: "09:19",
        durationMinutes: 42,
      },
      waitMinutes: 38,
      dateLabel,
      totalMinutes: 129,
    },
    {
      type: "transfer",
      transferStation: "松山湖北",
      leg1: {
        cityTrackId: 241,
        trainName: "C4702/3",
        fromStation: "樟木头东",
        toStation: "松山湖北",
        departTime: "07:10",
        arriveTime: "07:41",
        durationMinutes: 31,
      },
      leg2: {
        cityTrackId: 241,
        trainName: "S4842",
        fromStation: "松山湖北",
        toStation: "科韵路",
        departTime: "08:25",
        arriveTime: "09:19",
        durationMinutes: 54,
      },
      waitMinutes: 44,
      dateLabel,
      totalMinutes: 129,
    },
    {
      type: "transfer",
      transferStation: "常平南",
      leg1: {
        cityTrackId: 241,
        trainName: "C4702/3",
        fromStation: "樟木头东",
        toStation: "常平南",
        departTime: "07:10",
        arriveTime: "07:22",
        durationMinutes: 12,
      },
      leg2: {
        cityTrackId: 241,
        trainName: "S4842",
        fromStation: "常平南",
        toStation: "科韵路",
        departTime: "08:17",
        arriveTime: "09:19",
        durationMinutes: 62,
      },
      waitMinutes: 55,
      dateLabel,
      totalMinutes: 129,
    },
  ];
}
