import { TransferSolution } from "../../types";

export function scenarioZhangmutoudongToKeyunlu(dateLabel: string): TransferSolution[] {
  return [
    {
      type: "transfer",
      transferStations: ["广州莲花山"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4702/3",
          fromStation: "樟木头东",
          toStation: "广州莲花山",
          departTime: "07:10",
          arriveTime: "08:26",
          durationMinutes: 76,
        },
        {
          cityTrackId: 241,
          trainName: "S4812",
          fromStation: "广州莲花山",
          toStation: "科韵路",
          departTime: "08:31",
          arriveTime: "08:58",
          durationMinutes: 27,
        },
      ],
      waitMinutes: [5],
      dateLabel,
      totalMinutes: 108,
    },
    {
      type: "transfer",
      transferStations: ["东莞西"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4702/3",
          fromStation: "樟木头东",
          toStation: "东莞西",
          departTime: "07:10",
          arriveTime: "08:12",
          durationMinutes: 62,
        },
        {
          cityTrackId: 241,
          trainName: "S4812",
          fromStation: "东莞西",
          toStation: "科韵路",
          departTime: "08:18",
          arriveTime: "08:58",
          durationMinutes: 40,
        },
      ],
      waitMinutes: [6],
      dateLabel,
      totalMinutes: 108,
    },
    {
      type: "transfer",
      transferStations: ["麻涌"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4702/3",
          fromStation: "樟木头东",
          toStation: "麻涌",
          departTime: "07:10",
          arriveTime: "08:19",
          durationMinutes: 69,
        },
        {
          cityTrackId: 241,
          trainName: "S4812",
          fromStation: "麻涌",
          toStation: "科韵路",
          departTime: "08:25",
          arriveTime: "08:58",
          durationMinutes: 33,
        },
      ],
      waitMinutes: [6],
      dateLabel,
      totalMinutes: 108,
    },
    {
      type: "transfer",
      transferStations: ["西平西"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4702/3",
          fromStation: "樟木头东",
          toStation: "西平西",
          departTime: "07:10",
          arriveTime: "07:59",
          durationMinutes: 49,
        },
        {
          cityTrackId: 241,
          trainName: "S4842",
          fromStation: "西平西",
          toStation: "科韵路",
          departTime: "08:37",
          arriveTime: "09:19",
          durationMinutes: 42,
        },
      ],
      waitMinutes: [38],
      dateLabel,
      totalMinutes: 129,
    },
    {
      type: "transfer",
      transferStations: ["松山湖北"],
      legs: [
        {
          cityTrackId: 241,
          trainName: "C4702/3",
          fromStation: "樟木头东",
          toStation: "松山湖北",
          departTime: "07:10",
          arriveTime: "07:41",
          durationMinutes: 31,
        },
        {
          cityTrackId: 241,
          trainName: "S4842",
          fromStation: "松山湖北",
          toStation: "科韵路",
          departTime: "08:25",
          arriveTime: "09:19",
          durationMinutes: 54,
        },
      ],
      waitMinutes: [44],
      dateLabel,
      totalMinutes: 129,
    },
  ];
}
